[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
Chairmarks = "0ca39b1e-fe0b-4e98-acfc-b1656634c4de"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Groebner = "0b43b601-686d-58a3-8a1c-6623616c7cd4"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
ParamPunPam = "3e851597-e36f-45a9-af0a-b7781937992f"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
RationalFunctionFields = "73480bc8-48a2-41cc-880f-208b490ccf65"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StructuralIdentifiability = "220ca800-aa68-49bb-acd8-6037fa93a544"
